### ISSUE TITLE
Can't select game selection

### ISSUE THREAD

**Issue by RexBorova** [mmatyas/pegasus-theme-es2-simple#1]
Hey man. Great work on your front end! I've tried to use our port of the emulationstation theme, but when I  switch the the ES theme, it just shows the white box and black background, with no selection to choose from. Default theme works great tho, not sure if this is a bug in this theme, or if I'm possible just missing a step. Thank you for everything!

**Comment by mmatyas** [comment]
Hi, could you try updating the theme and Pegasus to the latest versions? There have been a few changes last week in both of them, which can cause issues like this with older releases.

**Comment by RexBorova** [comment]
That did the trick. Thank you!

**Comment by mmatyas** [comment]
You're welcome :)
