### ISSUE TITLE
Missing scrap image moves the gameLabels left

### ISSUE THREAD

**Issue by substring** [mmatyas/pegasus-theme-es2-simple#3]
Hi!

First of all: congratulations for all that work you've done so far with Pegasus. It looks veeeery promising, and I hope i'll be able to contribute further (I'm struggling really much with the theme tutorial, trying to match it up to the new API :sweat_smile: )

Regarding the theme: when the the boxart image is missing, the size is not "reserved", so the gameLabels are moved to the left. This is not comfortable for the eyes, and not like how ES renders it. Even if the box art is missing, it should be 256 pixels wide.

**Comment by mmatyas** [comment]
Ok, I've set a minimum and maximum width for the image, should be fine now.

Yeah there have been a few breaking changes lately with the themes and all, but as soon as I'm done with them I plan to update the docs. Sorry for the inconvenience!

**Comment by substring** [comment]
Don't be sorry, that was a great opportunity to dig further with QML and pegasus internals ! Anyway, the quality of the documentation is great already, just the api which is now really outdated.
