### ISSUE TITLE
Possible bug - logo's SVG is grayscale?

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-theme-es2-simple#5]
I tried using the WiiU logo from this thread: https://www.reddit.com/r/emulationstation/comments/6eikeb/launch_cemu_from_emulationstation_with_full_theme/ but the image comes out in grayscale.  I was a little surprised given the preview image shows the console logos in full color.

**Comment by mmatyas** [comment]
Seems to be fine for me:

![screenshot_2019-03-02_20-38-32_2](https://user-images.githubusercontent.com/4354863/53686742-64783b80-3d2b-11e9-818b-d3d20e97f58f.png)

Maybe a Windows bug? Can you check on other devices or platforms, eg. Android?

**Comment by mmatyas** [comment]
Confirmed on Windows, very interesting.
